### ISSUE TITLE
Copy to remote path with different name than local path

### ISSUE THREAD

**Issue by brneor** [zonuexe/emacs-auto-deployment#3]
When I try to copy a local file located on `/home/user/project/branch/file.txt` to remote path `/home/user/scripts/ `it keeps creating the `branch` folder and putting `file.txt` on it. Am I missing some configuration?

**Comment by zonuexe** [comment]
@hailbreno Probably [projectile](https://github.com/bbatsov/projectile) is unable to identify the root directory of your project.

The most easiest way is to run `git init` in your project's root directory, or instead place `.projectile` (which can be an empty file) instead.

Other methods can also be solved by writing the full path of your project in `copy-file-on-save-base-dir`. (It would be better to write in `.dir-locals.el` or` .dir-locals-2.el`)

**Comment by brneor** [comment]
Setting the `copy-file-on-save-base-dir` variable on my `.dir-locals.el` solves the issue. Thanks @zonuexe.
